# Generated by Django 4.2.1 on 2023-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_staff_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
