# Generated by Django 4.2.1 on 2023-07-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_staff_email_student_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="email",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="email",
            new_name="username",
        ),
    ]
