# Generated by Django 4.2.1 on 2023-07-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_email_staff_username_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"permissions": [("add_room_abdalla", "can add new room")]},
        ),
    ]
